# Logs a given user into a given OpenShift using the `oc` tools.
#
# REQUIRED VARIABLES
#   openshift_host     - OpenShift host to log into
#   openshift_username - OpenShift usernmae to log in as
#   openshift_password - OpenShift username password

- name: Verify 'openshift_host' defined
  fail:
    msg: "'openshift_host' must be defined"
  when: openshift_host is undefined

- name: Verify 'openshift_username' defined
  fail:
    msg: "'openshift_username' must be defined"
  when: openshift_username is undefined

- name: Verify 'openshift_password' defined
  fail:
    msg: "'openshift_password' must be defined"
  when: openshift_password is undefined

- name: Get current OpenShift user
  command: >
    {{ oc_tools }} whoami
  register: oc_whoami
  ignore_errors: True
  changed_when: False

- name: Log into OpenShift
  command: >
    {{ oc_tools }} login {{ openshift_host }} --username='{{ openshift_username }}' --password='{{ openshift_password }}'
  no_log: True
  when: oc_whoami.stdout != openshift_username
